### ISSUE TITLE
导出的html接口文档的表格单元格换行不美观的问题

### ISSUE THREAD

**Issue by wxlzmt** [YMFE/yapi#1072]
导出的html接口文档的表格单元格换行不美观的问题
服务器版本**1.7.0**

---

导出的文档是一个独立的html文件,未依赖其它任何外部css或js, 在html中有用到 `<tbody className="ant-table-tbody">` 和 `<thead class="ant-table-thead">` , 但是该样式并未定义.

---

**解决方案**
添加自定义样式
```css
tbody[className=ant-table-tbody] td,.ant-table-thead th{
    white-space: nowrap;
}
```

---

**建议**

导出时, html头部再添加一些适当的css
