### ISSUE TITLE
接口页面中，接口路径文字没有上下对齐

### ISSUE THREAD

**Issue by srzyhead** [YMFE/yapi#147]
## Version
官网demo版本

## What is expected
修改成对齐的样式

## Step to reproduce
访问http://yapi.demo.qunar.com/project/209/interface/api ，出现如下页面
![image](https://user-images.githubusercontent.com/1509615/35710982-7a9cbe48-07f5-11e8-99aa-8ded871d4fd6.png)
可见，get和接口路径名称没有对齐

修改建议：
```css
.table-interfacelist .path {
    width: 100%;
    display: inline-block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    padding-right: 24px;
}
```
当去掉上面css的display属性，显示就正常了

## Environment
官网demo版本
