### ISSUE TITLE
如何在k8s使用helm安装yapi

### ISSUE THREAD

**Issue by wjmmjr** [YMFE/yapi#2297]

**Comment by xjh1994** [comment]
用kompose把下面的docker-compose.yml转成helm格式，再用helm装即可
```
version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=xxx
      - YAPI_ADMIN_PASSWORD=xxx
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
    labels: 
      kompose.service.type: clusterip
      kompose.image-pull-policy: "Always"
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - mongo-db:/data/db
    expose:
      - 27017
    restart: unless-stopped
    labels: 
      kompose.service.type: clusterip
      kompose.image-pull-policy: "Always"
      
volumes:
  mongo-db:
```
