### ISSUE TITLE
yapi 所有问题解决一览

### ISSUE THREAD

**Issue by xwj-vic** [YMFE/yapi#2695]
所有问题看这里就可以解决了，折腾了好久总结出来的：https://blog.opendeveloper.cn/yapi

修复bug汇总：https://blog.opendeveloper.cn/yapi/bug

**Comment by 2513483494** [comment]
如何本地调试呢？按照说明安装好了本地的环境，但是运行npm run dev或者npm run build-client都会报错Cannot find module '../../config.json'
如何本地调试呢？

**Comment by xwj-vic** [comment]
config.json放错位置了，这个得按照yapi的教程来

**Comment by 2513483494** [comment]
> config.json放错位置了，这个得按照yapi的教程来

直接clone yapi的代码，按照你说的方式配置环境，安装依赖，然后npm run dev就会报这个错误，查看错误代码发现是config文件引入不对

**Comment by penghaihei** [comment]
我也是报了同样错误。
module.js:550
    throw err;
    ^

Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yuxin/Desktop/集团IT/前端项目/YApi/server/yapi.js:4:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
请问怎么解决

**Comment by penghaihei** [comment]
module.js:550
    throw err;
    ^

Error: Cannot find module '../../config.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/XXXX/Desktop/XXXXX/YApi/server/yapi.js:4:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by penghaihei** [comment]
我也报了同样的错误，请问怎么解决？

module.js:550
throw err;
^

Error: Cannot find module '../../config.json'
at Function.Module._resolveFilename (module.js:548:15)
at Function.Module._load (module.js:475:25)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object. (/Users/XXXX/Desktop/XXXXX/YApi/server/yapi.js:4:16)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)

**Comment by tmlx1990** [comment]
> 我也报了同样的错误，请问怎么解决？
> 
> module.js:550 throw err; ^
> 
> Error: Cannot find module '../../config.json' at Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Object. (/Users/XXXX/Desktop/XXXXX/YApi/server/yapi.js:4:16) at Module._compile (module.js:653:30) at Object.Module._extensions..js (module.js:664:10) at Module.load (module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3)

你的config.json放的位置不对

**Comment by tmlx1990** [comment]
> 我也报了同样的错误，请问怎么解决？
> 
> module.js:550 throw err; ^
> 
> Error: Cannot find module '../../config.json' at Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (internal/module.js:11:18) at Object. (/Users/XXXX/Desktop/XXXXX/YApi/server/yapi.js:4:16) at Module._compile (module.js:653:30) at Object.Module._extensions..js (module.js:664:10) at Module.load (module.js:566:32) at tryModuleLoad (module.js:506:12) at Function.Module._load (module.js:498:3)

参考下这个 ，里边有内网部署的步骤。下边还有目录结构。
https://hellosean1025.github.io/yapi/devops/index.html 

<img width="863" alt="image" src="https://github.com/YMFE/yapi/assets/5753992/b4f37573-a987-4eb2-b661-fa824ad13bd6">

**Comment by Lofanmi** [comment]
直接使用 docker-compose！我基于这个项目 https://github.com/fjc0k/docker-YApi ，替换了镜像，导入导出目前是正常了！感谢各位大佬们！！！

详细步骤如下：
1. 安装docker
2. 把以下内容，保存为 docker-compose.yml
3. docker-compose up
4. 访问 http://localhost:40001

```yaml
version: '3'

services:
  yapi-web:
    image: xuweijie1015/yapi:latest
    container_name: yapi-web
    ports:
      - 40001:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=邮箱@xx.com
      - YAPI_ADMIN_PASSWORD=密码
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ./data/db:/data/db
    expose:
      - 27017
    restart: unless-stopped
```
